appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: w+wejlDgkx7Uq33r5YDQkiQT0HHb1lY00UXEnvWifFB8YdOBJKezgPdFO9w5b88ATOjCTThcX0H8tI6doZFPkCqy0cjV/BQuzl8HdABHq4E/RkMKnja9zRqROQNyt3ImehK7JFfdwl+KJ+aw19hcKHLJhnulzLBZoWBmmMMRkeqYkrhI80JR9iw52wCLVWgmWStTbmY1Ya/5l1pePZJuwuibtAB+RWn6jjyGNkX+w2CGFYqrMvdZ8QvwF4kgMNxHB9LzP+jyA6MwzLbcFvSu2u/XLSxt2eq8nmTRtqV8lLhQnd8xLOx1JTtUuyVuuyttuMGabqSheMJrVzeeL3+LW0Wpe+9Grb+Z2xrtfp0uOAfh4YTIGEJyDOYQ5TaZLnMcvP5LF9lTk6XNZAqps9vlbm3oTgyGKfZ042JWs2JTpYcriC0USFmxX+WoNmhyHi60I6m90yaxfHPgLiAuf559PjTznu7JXY2WOV1PcC9lk4TEsQKDPutNsNPyV2seFYvKmWsjuKonBx2M9DfXT5mDp++p7j037GLSNwGz08T8C9I++x+Xr+oQvDMOnJgPDRs423ugCm36xDG0zdrUSOE5gLgllfCQe1+OYEt2XWVMVTFKLpFdT82r3syKOmG5gT83VRgq3InszORh+Lt7B3fus3VGEM5G7OqDC2XBAhHjvhQ=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
