travis:
  secure:
    BINSTAR_TOKEN: 0oYtD81ksjliaaYzgjAfpwXk1swm2FgbJHlOi/baQr5o97WRnVgH50a/pnLwey9dUHViTLGMdSW/Cv21o/EfHYpzeFDdNDZ45kJSb/i3uh75HWNJhx9/HEoMozBP0XMfv64RNdAgpETlW9UtVlpbk3inZWLO3PfStPqHSEHGqrwfovnFHO1f7yMo4kEv8xzzUhdXwyOhWWTKL5ZI+FC7vOL8skFh7dINl1JISvNtrB22W9z4hN3G17551NBfSsAmdE+wtKHfH87RmdFyjgtCEjkpapHOxWoDSP1dbrHd92Ty8Ept4qy8UcP7aZBqP9wgunnkKNLA9/NeMbLueHJYJXKgAK1eLH6AXVlwv73klHFKGAO6FICtVHnCBBnxfRvZYMIuACu7P8szfu1XVlRTbwoSDJdFntVpDaiSpBTBDcI7Wz+H+ERldliVGKpd2AC2WpOsQ3z2Xuv7l0y6+XmpwAXzseojDeY21YXlwVHkGITRoBSm2BCgBBgsPplQ2maA1sTrI9U5SptF5ntV+/00kyJ9f0R0GOgpJ+7Y9Dk2muUeZYY+XlkCtV+JqYMZYLcDoxgbS0KQmzphINA5WuD/FAWWi34vzAUCXKZK9XzTlAzsToK+MHpD50MTawcz3jpCOaOu0UjPYexaYhV6dKMdlpW3tZnC/tZK5pSeax1f3fk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
